// src/components/Footer.jsx
import { FooterData } from "./Data";

const Footer = () => {
  return (
    <>
      <div className="w-full mt-28 mb-5 min-h-full overflow-hidden border-primary-cylogo py-4">
        <div className="pt-2">
          {FooterData.map((d, index) => (
            <div key={index}>
              <div className="text-white text-lg text-center md:text-left font-novaSquare">
                {d.copyright} {d.year}
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Footer;

// src/components/Footer.vue
<template>
    <div class="px-6 lg:ps-24 py-5">
        <div v-for="footer in footer" :key="footer.id" class="text-slate-700 font-bold font-lobstertwo text-lg mx-auto">
            <div>
                <div class="text-white text-center lg:text-center text-base leading-loose tracking-wider font-poiretone">
                    {{ footer.copyright }} {{ footer.year }}
                </div>
            </div>
        </div>
    </div>
</template>
  
<script>
import footer from '../assets/data/footer';

export default {
    data() {
        return {
            footer: footer,
        };
    },
};
</script>
